### ISSUE TITLE
Add sdkVersion in client-register call 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-go#10]
As specified in https://github.com/Unleash/unleash/blob/master/docs/api/client/register-api.md clients should now include sdk type and version identifier. 

The value of the of this field should be picked up from `??` and look like:
`sdkVersion: unleash-client-go:3.x.z`

**Comment by jrbarron** [comment]
@ivarconr I've started implementing this now, but the Go version of the client hasn't had a version number until now (it's not used when publishing Go packages). Should I start at v1.0.0 or jump to v2.0.0 since that's where the other clients (and the server) are?

**Comment by ivarconr** [comment]
For simplicity I would say that the go-client should start at v2.0.0. It makes it easier to communicate. 

(But there is nothing that says that clients and servers needs to follow the same versioning, but then it must be clearly stated which versions that fits together somewhere).

**Comment by jrbarron** [comment]
This was fixed in 10fce9dc.
