### ISSUE TITLE
Is there a way to get all the feature flags for a project, not just one at a time?

### ISSUE THREAD

**Issue by ozzieperez** [Unleash/unleash-client-go#101]
Thanks so much for making this client available. Been using it on a project and we're running into an issue where calls to "IsEnabled" start to hang after our server has been running for a few days. We've got about 20 feature flags and loop through an array to fetch each of them every time a user signs into the web app. Restarting the server fixes the issue until it happens again.

I was reading over the [feature-toggle docs](https://docs.getunleash.io/api/client/features#get-specific-feature-toggle) and it says that querying for a specific feature toggle is not the intended way to use Unleash. Under the "Get specific feature toggle" section on that page it says:

> **Get specific feature toggle**
> Used to fetch details about a specific feature toggle. This is mainly provided to make it easy to debug the API and should not be used by the client implementations.

Does this client currently support the recommended way from [this section](https://docs.getunleash.io/api/client/features#fetching-feature-toggles) of the same page, where it says:

> This endpoint is the one all clients should use to fetch all available feature toggles from the unleash-server. The response returns all active feature toggles and their current strategy configuration. 

It allows for certain filters:

> tag - filters for features tagged with tag
> project - filters for features belonging to project
> namePrefix - filters for features beginning with prefix

Thanks for your all you do and in advance for any guidance!

**Comment by kjvalencik** [comment]
It [uses that endpoint](https://github.com/Unleash/unleash-client-go/blob/d0a484706ab1d1b491e92e07b431c2df7d3ed38a/utils.go#L31).

This sounds like maybe there is a deadlock? `IsEnabled` does [take a read lock](https://github.com/Unleash/unleash-client-go/blob/d0a484706ab1d1b491e92e07b431c2df7d3ed38a/repository.go#L142).

**Comment by ozzieperez** [comment]
@kjvalencik  thanks for your feedback. I just realized the version we have installed is v2, which is why I was wondering why [ListFeatures](https://github.com/Unleash/unleash-client-go/blob/d0a484706ab1d1b491e92e07b431c2df7d3ed38a/client.go#L409) wasn't showing up as an option. 

![image](https://user-images.githubusercontent.com/174189/157795646-c0cfb685-8238-489e-b40e-5858ea6dfda8.png)

Thanks again! ✌️✊
