### ISSUE TITLE
Update link to GoDoc

### ISSUE THREAD

**Issue by a-rhodes** [Unleash/unleash-client-go#125]
https://github.com/Unleash/unleash-client-go/blob/5a7a36f432462ab880a69070ccb2422381994a5d/README.md?plain=1#L1

Current link directs you to the old docs. Took me a while to find that there was a V3 doc site with all the new functionality.

**Comment by gastonfournier** [comment]
Hi @a-rhodes let me know if the linked PR solves the issue, otherwise, just let me know!

**Comment by a-rhodes** [comment]
Looks good!
