### ISSUE TITLE
openfeature

### ISSUE THREAD

**Issue by damianoneill** [Unleash/unleash-client-go#133]
### Describe the feature request

Are there any plans to develop a https://openfeature.dev/  provider implementation for this SDK?

### Background

We are evaluating different feature toggle implementations.  Standardising on a common interface is important to our organisation. In the FT space we believe that openfeature will be that standard, similar to opentelemetry has become for telemetry, metrics and logs.

**Comment by sjaanus** [comment]
Hey @damianoneill . While we currently don't have immediate plans to pursue this opportunity, we are actively monitoring the market and maintain a keen interest in OpenFeature.
