### ISSUE TITLE
Back-off strategy for calling Unleash

### ISSUE THREAD

**Issue by dramamask** [Unleash/unleash-client-go#141]
### Describe the feature request

I'd like to see some kind of back-off strategy when it comes to calling the Unleash API. Basically a circuit breaker pattern or something to that extend. Right now the code seems to immediately retry calling Unleash after a failed attempt. I'd also be happy with a setting where I can determine the retry time-out.

### Background

We recently had an issue where we couldn't reach Unleash. The unleash go client kept trying to call Unleash, about every 50 milliseconds (i.e. about 20 times per second). This lead to literally millions of error messages in our logs. Our DevOps guys were not happy.

### Solution suggestions

You could implement a circuit-breaker pattern, or maybe just a configurable retry time-out.

**Comment by daveleek** [comment]
Hi @dramamask, thanks for raising this. This is a planned project for Q4 - I've added it to the public roadmap

Issue: https://github.com/Unleash/unleash/issues/4904
Public roadmap: https://github.com/orgs/Unleash/projects/10
