### ISSUE TITLE
Missing v3.9.0 Release Notes 

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash-client-go#148]
### Describe the bug

Moved from https://github.com/orgs/Unleash/discussions/5142

> Looks like there is a new v3.9.0 tag that Dependabot is picking up for https://github.com/Unleash/unleash-client-go but there isn't a published release, can we get those notes?

Also, `v4.0` is not marked as _latest_ in GitHub Releases.

**Comment by gastonfournier** [comment]
There's a new release 3.9.1 and the latest tag is now 4.0.1. Both have release notes and 3.9.0 was removed for a reason. Dependabot should now be picking up 3.9.1 or 4.0.1.
