### ISSUE TITLE
Deadlock in metrics

### ISSUE THREAD

**Issue by yukw777** [Unleash/unleash-client-go#15]
There's a deadlock in how the go client handles metrics data, specifically when it handles the "sent" event. There are other issues in the codebase that were uncovered during debugging, so I'll list all of them here for now, but I'm happy to make a separate issue for each if necessary.

The deadlock happens when you don't pass in an "optional" event listener (`WithListener`) when initializing the client. The unbuffered sent channel receives a value
https://github.com/Unleash/unleash-client-go/blob/c586a9e5f31e9788ba0dc3f0726150717330d971/metrics.go#L186
, but b/c the event listener is nil, the receiver is never started
https://github.com/Unleash/unleash-client-go/blob/c586a9e5f31e9788ba0dc3f0726150717330d971/client.go#L97-L110
, so the next time a payload is sent to the sent channel, it blocks.

There are some other issues related to this bug.

1. `WithDisableMetrics` doesn't work, b/c the value doesn't get passed into metrics from the clinet.
https://github.com/Unleash/unleash-client-go/blob/c586a9e5f31e9788ba0dc3f0726150717330d971/client.go#L163-L171
1. If you pass in the value down to metrics, you get a nil pointer exception b/c the timer is never initialized.
https://github.com/Unleash/unleash-client-go/blob/c586a9e5f31e9788ba0dc3f0726150717330d971/metrics.go#L95-L99
1. Setting metrics interval to 0 doesn't work either since it now blocks on other channels.
https://github.com/Unleash/unleash-client-go/blob/c586a9e5f31e9788ba0dc3f0726150717330d971/metrics.go#L80-L84
1. Metrics is too tightly coupled to the client. Proper dependency inversion would help here.

The only true workaround that works right now is to set a listener, even if it's a noop.

Happy to help out in anyway I can. Thanks!

**Comment by jrbarron** [comment]
@yukw777 Thanks for the report. This deadlock issue is known and documented here (last sentence under "Basics"):

https://godoc.org/github.com/Unleash/unleash-client-go#hdr-Basics

It was a side effect of the API design where I wanted to force people to use a listener so as not to ignore errors which as you know is bad practice in Go. In retrospect, this may have been a mistake so I have contemplated changing it, perhaps in the `v3` branch.

The additional bugs you mention there certainly sound valid so I'll try to take a look at those when I get some time. I will happily accept a PR for these too if you have something ready. I've also starting writing some unit tests for the metrics struct now so hopefully that will catch some of these issues.

Thanks for the great report!

**Comment by jrbarron** [comment]
The bugs relating to disabling metrics and also the deadlocks (except for the nil Listener which is documented) should now be fixed so I'm closing this.
