### ISSUE TITLE
Update API endoint paths for Unleash 3.x 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-go#16]
The next version of Unleash has changed the API endpoint for the client calls. Next version of the client should always use the `/api/client` prefix for all requests.

This will only affect the features path which now will be: `http://unleash.host.com/api/client/features`. 

(Metrics and register paths already has the correct prefix. )

Docs: 
https://github.com/Unleash/unleash/tree/master/docs/api/client

**Comment by jrbarron** [comment]
This should already be implemented in the `v3` branch: https://github.com/Unleash/unleash-client-go/commit/6e30466857590ac27c8ab70438f4a45066b12a4f

@ivarconr Do we have a v3 server up and running that I can use for the unit tests?

**Comment by ivarconr** [comment]
unleash.herokuapp.com (but it currently has enabled legacy paths also)
