### ISSUE TITLE
Another deadlock in metrics

### ISSUE THREAD

**Issue by yukw777** [Unleash/unleash-client-go#17]
Hello everyone, I've found another deadlock in the metrics event loop. It happens if the unleash server (`./client/metrics`) returns 404. Erroneous config value was the culprit for me.

1. The client attempts to send metrics but gets 404, so it tries to stop.
https://github.com/Unleash/unleash-client-go/blob/be883ea1af714aff427d0668dbd4fc549d4f701c/metrics.go#L176-L180

2. `stop()` sends `true` to `m.stopped` channel, and blocks.
https://github.com/Unleash/unleash-client-go/blob/be883ea1af714aff427d0668dbd4fc549d4f701c/metrics.go#L106

3. At this point, `sync()` is also blocked, since `sendMetrics()` is blocked. But `sync()` is the one that could free everything up by taking the value from `m.stopped`. Hence, deadlock.
https://github.com/Unleash/unleash-client-go/blob/be883ea1af714aff427d0668dbd4fc549d4f701c/metrics.go#L124-L129

**Comment by jrbarron** [comment]
After merging #52 this issue seems to be resolved.
