### ISSUE TITLE
Support running in offline mode (e.g. bootstrap feature toggles from a file)

### ISSUE THREAD

**Issue by vgrigoruk** [Unleash/unleash-client-go#185]
### Describe the feature request

Unleash NodeJS sdk has the following functionality that supports running in "offline" mode:
- https://docs.getunleash.io/reference/sdks/node#bootstrap
- https://docs.getunleash.io/reference/sdks/node#custom-repository
- setting `refreshInterval = 0` disables refreshing the toggles from the upstream URL.

Using these options, it is possible to run the the client w/o network access to Unleash API. It would be nice if unleash-client-go also supports this.

### Background

Running the SDK in offline mode is necessary to support the following use-cases:
- running the apps in offline environments, where toggle updates only occur when a new version of the code is deployed
- support determinism in local development and CI environment while keeping the setup simple (avoid adding unleash-edge running in "offline" mode to local dev/test environment).

**Comment by FredrikOseberg** [comment]
@vgrigoruk The Golang SDK also supports bootstrapping from a file. See [this](https://github.com/Unleash/unleash-client-go?tab=readme-ov-file#preloading-feature-toggles) section of the README.md. It should also support setting refreshInterval to 0 via configOptions.

**Comment by santiaago** [comment]
FYI, in `newRepository`, `repository.go`

```go
repo := &repository{
    options:            options,
    ...
    refreshTicker:      time.NewTicker(options.refreshInterval),
    ...
}
```

`time.NewTicker` panics if `refreshInterval` is set to 0.
