### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by italolelis** [Unleash/unleash-client-go#24]
Hello there,

Thank you for this great project. I was looking into the commits on this repo and it's been a while since the last one. Is this still an active project?
I had some problems with the metrics that were blocking because some channels were stuck. If you need any help in maintain it I would be glad to help.

**Comment by sveisvei** [comment]
Thank you @italolelis! We are more than open for help/improvements.

**Comment by jrbarron** [comment]
@italolelis Yes, still alive, but have been a bit busy lately :) The metrics will block if you do not specify a listener:

https://godoc.org/github.com/Unleash/unleash-client-go#hdr-Basics

This was a design choice to encourage people not to ignore errors, but in retrospect it may not have been the right choice. We are always welcome to new contributors so please feel free to help!

**Comment by habibridho** [comment]
I think this might be better to be included in the Getting Started.

**Comment by jrbarron** [comment]
@habibridho Totally agree, that makes sense and is infact an oversight. Would you like to send a PR or should I do it?

**Comment by habibridho** [comment]
@jrbarron I'll submit a PR

**Comment by italolelis** [comment]
@jrbarron Thank you a lot for the explanation. Yes, I think if this is written on the `Getting Started` section it will be helpful.

I'd be very glad to help in any issues 👍 
Feel free to close the issue. Thanks everyone.

**Comment by jrbarron** [comment]
Ok, I've merged the PR now that updates the "Getting Started" section with the relevant info so I'll go ahead and close the issue. Thanks for the feedback and contribution guys! 🙇
