### ISSUE TITLE
Implement test-runner for client-specification.

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-go#26]
So we I finally had the time to defining a set of client specifications, which defines what the expected result should be for a given set of feature toggles and a given Unleash context. The idea is that they shall ensure correct behaviour of clients across languages.

The specifications lives inside: https://github.com/Unleash/client-specification

The node and java client already implements support for automatically running the test cases as part of the CI validation. 

Would be awesome if this client also could leverage the specifications. This will defenetly be used for v4, which will add new capabilities to the Unleash protocol.

**Comment by jrbarron** [comment]
This is now supported in the `v3` branch.
