### ISSUE TITLE
Make Unleash Globally accessible

### ISSUE THREAD

**Issue by shivid** [Unleash/unleash-client-go#3]
Unleash takes some time to initialize before I can actually run Unleash.IsEnabled, but I don't have a globally accessible method to do that. Right now my only option is to make a NewClient for every package and access the IsReady channel that way. I'm sure there is a more elegant solution for this. I'm thinking of having a global *Client object and accessing that through Unleash instead of initializing a NewClient every time. This way the user can initialize a global Client and add new ones as needed. In most cases one Client would be enough. At the least have a function to access the IsReady channel for the defaultClient instance.

**Comment by ivarconr** [comment]
Sounds reasonable, but im not a go expert. What do think @jrbarron ?

**Comment by shivid** [comment]
I made a Pull Request with a possible solution as well.

**Comment by shividhar** [comment]
I made a Pull Request with a possible solution as well.

**Comment by jrbarron** [comment]
@shivid I pushed a patch that should address your use case to this branch: https://github.com/Unleash/unleash-client-go/tree/feature/wait-for-ready Could you maybe check it out and give it a go before I merge?

**Comment by jrbarron** [comment]
We now have a `WaitForReady` function in the `v3` branch which I think covers this use case so closing this issue.
