### ISSUE TITLE
Internal only helpers.go makes custom gradual rollout strategies difficult/messy

### ISSUE THREAD

**Issue by GrgDev** [Unleash/unleash-client-go#42]
I am currently writing some custom strategies that are simply gradual rollout strategies similar to the built in one for user IDs but these are keyed off of different data specific to my use case. I want to make sure that my gradual rollout strategy uses the same normalization, rounding, etc. that the built in gradual rollout strategies use.

However, that logic is defined inside of `internal/strategies/helpers.go` which means I don't get access to that by just importing. I have to copy & paste the helper.go code into my repo and remember to occasionally check to see if there's been any code changes to the helper.go file in this repo once in awhile. I believe this is less than ideal. I would appreciate it if these helper functions could be exported in some manner so as to make them available for import into custom strategies.

**Comment by jrbarron** [comment]
@GrgDev Yup, that makes sense. How about we move them to the `strategy` package and export them? Sound like the right place? Are you using the `v3` version of the client? Do you want to make a PR or should I do it?

**Comment by GrgDev** [comment]
I am currently using the v3 client. Also I can try to make a PR if you want, but I just learned Go about two weeks ago so... feel free to make a call on that risk factor.

**Comment by GrgDev** [comment]
I'll give it a shot.

**Comment by GrgDev** [comment]
Oh, I answered the last question but not the others. Yes, I am using the v3 version of the client. Also that package location sounds logical to me. I'll give making a PR a shot.

**Comment by FredrikOseberg** [comment]
Move strategies package from internal folder structure to -> ROOTDIR/strategies/[packagefiles.go]
