### ISSUE TITLE
feat: add support static context fields

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-go#44]
In order to prepare the SDKS for [strategy constraints](https://github.com/Unleash/unleash/issues/442) we need to introduce two new fields in the [Unleash Context](https://unleash.github.io/docs/unleash_context) 

- `environment` (default value is "default")
- `appName` (already a required config parameter)

Both these static context fields should be configured at initialisation of the unleash SDK and be set as default values of the Unleash Context provided to the strategy implementations. The user is allowed to override these values in the context object at runtime (this is required to be backward compatible). 

This support should be possible to add without breaking any contract and should be released as a minor version (3.3.x).

**Comment by jrbarron** [comment]
Fixed with #56
