### ISSUE TITLE
feat: add Variant support

### ISSUE THREAD

**Issue by mikhail** [Unleash/unleash-client-go#45]
Unleash 3.2.0 created a beta functionality for [Variants](https://github.com/Unleash/unleash/blob/master/CHANGELOG.md#320). Node and Java clients already seem to [support it](https://github.com/Unleash/unleash/blob/a34b991a2b52662447efab5768373a9f0f863aed/docs/beta-features.md#client-sdk-support).

**Comment by jrbarron** [comment]
@mikhail We have started working on this in the `wip/v4` branch, but we're a bit behind the other clients. I'll try to find some time to dedicate to this in the next weeks.

**Comment by silviogreuel** [comment]
Could I help? I'm currently tasking this on https://github.com/stiano/unleash-client-dotnet/pull/14

**Comment by konfortes** [comment]
https://github.com/Unleash/unleash-client-go/pull/69
