### ISSUE TITLE
failing spec tests

### ISSUE THREAD

**Issue by konfortes** [Unleash/unleash-client-go#67]
Hey, 
It's been a while since I worked with Golang and I'm not familiar with testify. 
maybe I'm missing something but when running go test (after running make and go mod download) it is failing on missing file `testdata/client-specification/specifications/index.json`

**Comment by tormoder** [comment]
You'll need to clone the specification repository to `./testdata` before running the tests.
See https://github.com/Unleash/unleash-client-go/blob/v3/.travis.yml#L18.
