### ISSUE TITLE
Always getting flase

### ISSUE THREAD

**Issue by itairegev** [Unleash/unleash-client-go#7]
using the unleash node api, everything works,
when trying the same on the go api, i always get false on the IsEnabled function.

package main
import (
        "fmt"
        "time"
        "github.com/Unleash/unleash-client-go"
)
func init() {
        fmt.Println("init")
        unleash.Initialize(
                unleash.WithListener(&unleash.DebugListener{}),

                unleash.WithAppName("my-application"),
                unleash.WithUrl("http://unleash.herokuapp.com/api/"),
        )
        fmt.Println("end of init")
}
func main() {
        fmt.Println("main")
        i := 0
        for i < 10 {
                time.Sleep(time.Second * 10)
                fmt.Printf("%v\n",unleash.IsEnabled("AwesomeFeature"))
                i = i+1
        }

}

**Comment by itairegev** [comment]
found the bug....
client.go line #243 should be replaced from
		if foundStrategy.IsEnabled(f.Parameters, opts.ctx) {

to
		if foundStrategy.IsEnabled(s.Parameters, opts.ctx) {

**Comment by SimenB** [comment]
Can you send a PR (and a test for it)?

/cc @jbarron

**Comment by SimenB** [comment]
Hah, you _did_ send a PR!

**Comment by jrbarron** [comment]
Wow, that's quite an embarrassing bug. I was certain I tested this manually, but that code clearly would never have worked. In fact, I don't know why the `Features` struct even has a `Parameters` field. I'll clean that up when I am back from vacation and make an effort to increase the test coverage.

@itairegev Thanks for for the bug report and the fix!

**Comment by itairegev** [comment]
I'll create a test as well, should be easy

**Comment by itairegev** [comment]
@jrbarron i can't make the metrics work as well, do i need to initialize something else? i'll try to debug and understand
