### ISSUE TITLE
Unleash client go efficiency

### ISSUE THREAD

**Issue by avirogalsky** [Unleash/unleash-client-go#72]
Current implementation requires finding client supported strategies for toggle defined strategies **for each IsEnabled call**

	for _, s := range f.Strategies {
		foundStrategy := uc.getStrategy(s.Name)
		if foundStrategy == nil {
			// TODO: warnOnce missingStrategy
			continue
		}
		if constraints.Check(ctx, s.Constraints) && foundStrategy.IsEnabled(s.Parameters, ctx) {
			return true
		}
	}

It very ineffective especially for lists, where for each toggle it parses one string to list of values and search for some value.
It will have a big input in hi hit ratios cases
I suggest to initialize the relevant strategies for each toggle once the toggle fetched from api.

**Comment by jrbarron** [comment]
Hi @avirogalsky, thanks for the report. The Go version of the client was based on the Node version of the client which behaves the same way:

https://github.com/Unleash/unleash-client-node/blob/master/src/client.ts#L84-L100

I agree with you that it is more efficient to set the strategies after the list of feature toggles, but this obviously increases the complexity as well. If you or someone else wants to implement a PR for this, we can discuss the implementation and see if it is worth it.

**Comment by ivarconr** [comment]
The JavaClient actually initializes a "map" for direct access to each strategy. 

Also: would be good to actual measure this, as the number of strategies are expected to be low.

**Comment by avirogalsky** [comment]
I have prepared a branch for it, I just cannot push it to here...
I can open PR on it and we'll discuss above that
So if it will be ok for you guys I will add tests + documentation, and merge

**Comment by avirogalsky** [comment]
I think i need access right to upload a branch... it won't let me now

**Comment by avirogalsky** [comment]
@ivarconr @jrbarron see the PR:
https://github.com/Unleash/unleash-client-go/pull/73
we can discuss here or on slack about that....
