### ISSUE TITLE
Unable to get latest changes with go.mod

### ISSUE THREAD

**Issue by ddelger** [Unleash/unleash-client-go#84]
I am unable to pull in the latest changes, most notably for me the variant changes, using dependency management and go.mod. It continues to revert to the v3.1.1 tag applied a couple of years ago.

I have tried using a pseudo-version and pinning to the latest commit but am unable to do so with the v3 branch.

Can a new tag be applied to the latest changeset to aid in dependency management?

**Comment by ivarconr** [comment]
thats sounds like a good step. What do you think @jrbarron and @FredrikOseberg ?

**Comment by FredrikOseberg** [comment]
Tags are now being published on every release.
