### ISSUE TITLE
fix: GetVariant does not accept custom context

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-go#87]
In [client.go#L302](https://github.com/Unleash/unleash-client-go/blob/v3/client.go#L302) we should also apply user provided context fields to the getVariant function:

Something like this
```go
ctx := uc.staticContext
if opts.ctx != nil {
    ctx = ctx.Override(*opts.ctx)
}
```

**Comment by FredrikOseberg** [comment]
Fixed in #88
